[package]
name = "media_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.12.1"
turbosql = "0.10.0"
once_cell = "1.19.0"
